version: "{branch}-{build}"
skip_tags: true
shallow_clone: true
cache:
  - C:\ProgramData\chocolatey\bin                                                                                                     
  - C:\ProgramData\chocolatey\lib
os: Visual Studio 2015
platform:
  - Any CPU
configuration:
  - Release
environment:
  matrix:
    - TARGET: net452
    - TARGET: netcoreapp1.0
    - TARGET: msbuild-net45

build:
  project: src\Dse.sln
  verbosity: minimal
  
test_script:

  - IF "%TARGET%" NEQ "msbuild-net45" dotnet restore && dotnet test src\Dse.Test.Unit -c Release -f %TARGET% --result=TestResult.xml
  - IF "%TARGET%" == "msbuild-net45" nunit3-console src\Dse.Test.Unit\bin\Release\Dse.Test.Unit.dll --result=TestResult.xml

after_test:
  - ps: >-
      if($true)
      {
        $wc = New-Object 'System.Net.WebClient'
        $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit3/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestResult.xml))
      }

on_failure:
  - ps: >-
      Write-Host "Build failed"