version: "{branch}-{build}"
skip_tags: true
shallow_clone: true
cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
image: Visual Studio 2017
environment:
  appveyor_build_worker_cloud: gce
  NUNIT_PATH: nunit3-console
  matrix:
    - TARGET: net452
      CI_TYPE: UNIT
      PROJECT: Dse.Test.Unit
    - TARGET: netcoreapp2.0
      CI_TYPE: UNIT
      PROJECT: Dse.Test.Unit

install:
  - ps: choco install -y xmlstarlet

build_script:
  - ps: dotnet restore src
  - ps: dotnet build src\Dse.sln -c Release

test_script:
  - ps: dotnet test src\${env:PROJECT}\${env:PROJECT}.csproj -c Release -f $env:TARGET --logger "trx;LogFileName=..\..\..\TestResult.xml"
on_failure:
  - ps: |
      Write-Host "Build failed"
on_finish:
  - ps: |
      xml tr tools\trx-to-junit.xslt TestResult.xml > ResultsJUnit.xml
      $wc = New-Object 'System.Net.WebClient'
      $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\ResultsJUnit.xml))
